# Generated by Django 6.0 on 2026-01-07 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name_plural': '2. Subcategorías'},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'verbose_name_plural': '3. Tipos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Alerta de Stock Bajo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('tipo', models.CharField(choices=[('entrada', '📥 Entrada (Compra/Devolución)'), ('salida', '📤 Salida (Venta/Pérdida)')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo (Opcional)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Historial de Inventario',
                'verbose_name_plural': '📊 Control de Stock (Entradas/Salidas)',
            },
        ),
    ]
