# Generated by Django 6.0 on 2026-01-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_subcategoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='variaciones/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='inventario.producto')),
            ],
        ),
    ]
