# Generated by Django 6.0 on 2026-01-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_variacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Producto Visible?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Tono/Color'),
        ),
    ]
