# Generated by Django 6.0 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_activo_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacion',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cant. Disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Total'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='variaciones/', verbose_name='Foto del Tono'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Color / Tono / Talla'),
        ),
    ]
