# Generated by Django 6.0 on 2026-01-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_variacion_stock_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marcas/', verbose_name='Logo de la Marca (Opcional)')),
            ],
            options={
                'verbose_name_plural': '⭐ Marcas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca', verbose_name='Marca'),
        ),
    ]
