# Generated by Django 6.0 on 2026-01-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_categoria_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('MERCADERIA', 'Compra de Mercadería'), ('SERVICIOS', 'Luz/Agua/Internet'), ('PUBLICIDAD', 'Publicidad/Marketing'), ('OTROS', 'Otros Gastos')], default='MERCADERIA', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
