# Generated by Django 6.0 on 2026-02-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='canton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=10, verbose_name='Costo Envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='map_link',
            field=models.TextField(blank=True, null=True, verbose_name='Link Mapa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_destinatario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Exacta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente 🕒'), ('EN_CAMINO', 'En Camino 🚚'), ('ENTREGADO', 'Entregado ✅'), ('CANCELADO', 'Cancelado ❌')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
