# Generated by Django 6.0 on 2026-02-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_categoria_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='variacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
